version: '3'
services:
  container1:
    build:
      context: .
      dockerfile: dockerfile-ping
    depends_on:
      - container2
    networks:
      - mynetwork

  container2:
    build:
      context: .
      dockerfile: dockerfile-pinged
    networks:
      - mynetwork

networks:
  mynetwork:
